spring.application.name=Server

spring.datasource.url=jdbc:mysql://localhost:3306/databasequanao?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# 1h in millisecond
security.jwt.expiration-time=3600000

# ================= VNPAY SANDBOX (điền thông tin thực tế của bạn) ================
vnpay.tmnCode=7ZHENRO5
vnpay.hashSecret=1LEFQSO1HVGJA5L69SD64E6NJSHHF3U1
vnpay.payUrl=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.returnUrl=https://ginette-uncomparable-adequately.ngrok-free.dev/payments/vnpay/return
vnpay.frontendReturnUrl=http://localhost:5173/payment/vnpay-return
vnpay.ipnUrl=https://ginette-uncomparable-adequately.ngrok-free.dev/payments/vnpay/ipn

# ================= MoMo SANDBOX (điền thông tin thực tế từ MoMo Developer) ================
#momo.partnerCode=YOUR_MOMO_PARTNER_CODE
#momo.accessKey=YOUR_MOMO_ACCESS_KEY
#momo.secretKey=YOUR_MOMO_SECRET_KEY
#momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
#momo.redirectUrl=https://abc123.ngrok-free.app/payments/momo/return
#momo.ipnUrl=https://abc123.ngrok-free.app/payments/momo/ipn

# Spring Mail (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# T�n v� ??a ch? hi?n th? khi g?i email
app.mail.from=your-email@gmail.com
app.mail.from-name=Shop Support

# ?????????????????????????????????????????????????????????????
# L?u �: Gmail c?n d�ng App Password (kh�ng ph?i password th??ng)
# B?t t?i: Google Account ? Security ? 2-Step Verification ? App passwords